# Generated by Django 6.0.5 on 2026-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='common_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
