# Generated by Django 6.0.5 on 2026-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_common_image_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careinstruction',
            name='instruction_text',
            field=models.TextField(),
        ),
    ]
