# Generated by Django 6.0.5 on 2026-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_subcategory_sub_categor_categor_e70bb6_idx_and_more'),
        ('products', '0003_alter_careinstruction_instruction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_refurbished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_refurbished'], name='products_is_refu_b639a9_idx'),
        ),
    ]
