# Generated by Django 6.0.5 on 2026-05-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_update_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subcategory',
            name='sub_categor_categor_e70bb6_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_status_dda6e6_idx',
            old_name='categories_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='sub_categor_parent__ba116c_idx',
            old_name='sub_cat_parent_idx',
        ),
    ]
